FROM openjdk
MAINTAINER Mohamed Reda Bencheikh <bencheikh.mohamed.reda@gmail.com>
ADD expertus-eureka-1.0-SNAPSHOT.jar expertus-eureka-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/expertus-eureka-1.0-SNAPSHOT.jar"]
EXPOSE 8761