FROM openjdk
MAINTAINER Mohamed Reda Bencheikh <bencheikh.mohamed.reda@gmail.com>
ADD ms-customer-query-1.0-SNAPSHOT.jar ms-customer-query-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/ms-customer-query-1.0-SNAPSHOT.jar"]
EXPOSE 8089