FROM openjdk
MAINTAINER Mohamed Reda Bencheikh <bencheikh.mohamed.reda@gmail.com>
ADD expertus-gateway-1.0-SNAPSHOT.jar expertus-gateway-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/expertus-gateway-1.0-SNAPSHOT.jar"]
EXPOSE 8762