spring:
  application:
    name: zipkin-service

server:
  port: ${PORT:9411}

management:
  security:
    enabled: false

zipkin:
  self-tracing:
    # Set to true to enable self-tracing.
    enabled: ${SELF_TRACING_ENABLED:false}

#logging:
#  pattern:
#    level: %d{ABSOLUTE} [%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"