FROM openjdk
MAINTAINER Mohamed Reda Bencheikh <bencheikh.mohamed.reda@gmail.com>
ADD expertus-zipkin-1.0-SNAPSHOT.jar expertus-zipkin-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/expertus-zipkin-1.0-SNAPSHOT.jar"]
EXPOSE 9411