FROM openjdk
MAINTAINER Mohamed Reda Bencheikh <bencheikh.mohamed.reda@gmail.com>
ADD ms-account-query-1.0-SNAPSHOT.jar ms-account-query-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/ms-account-query-1.0-SNAPSHOT.jar"]
EXPOSE 8087